// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6N5OyCjwueLNgEC2l7BeU_rauZm7r2qM',
    appId: '1:694326366389:web:15a83fe7ae2aeff225aefc',
    messagingSenderId: '694326366389',
    projectId: 'stories-english-4c485',
    authDomain: 'stories-english-4c485.firebaseapp.com',
    databaseURL: 'https://stories-english-4c485-default-rtdb.firebaseio.com',
    storageBucket: 'stories-english-4c485.appspot.com',
    measurementId: 'G-FKYFRXRWBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfd4V-TDeppXsEFdZ7nV5mixCtNCFED3Q',
    appId: '1:694326366389:android:714538069010608725aefc',
    messagingSenderId: '694326366389',
    projectId: 'stories-english-4c485',
    databaseURL: 'https://stories-english-4c485-default-rtdb.firebaseio.com',
    storageBucket: 'stories-english-4c485.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFfu4MwvXbyK7fGi32bQY35tZJugxSgGY',
    appId: '1:694326366389:ios:33f5302612f7cd4525aefc',
    messagingSenderId: '694326366389',
    projectId: 'stories-english-4c485',
    databaseURL: 'https://stories-english-4c485-default-rtdb.firebaseio.com',
    storageBucket: 'stories-english-4c485.appspot.com',
    androidClientId: '694326366389-0qvu9uplj0l9e9ctfdf341i83539sqca.apps.googleusercontent.com',
    iosClientId: '694326366389-t7a3itrvgghi2i7bd7a14i90d1i79lgq.apps.googleusercontent.com',
    iosBundleId: 'com.storynorys.storynory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6N5OyCjwueLNgEC2l7BeU_rauZm7r2qM',
    appId: '1:694326366389:web:fb3b5cb96d9e5e9525aefc',
    messagingSenderId: '694326366389',
    projectId: 'stories-english-4c485',
    authDomain: 'stories-english-4c485.firebaseapp.com',
    databaseURL: 'https://stories-english-4c485-default-rtdb.firebaseio.com',
    storageBucket: 'stories-english-4c485.appspot.com',
    measurementId: 'G-Z66M22403M',
  );
}
